services:
  db:
    image: postgres:16-alpine
    container_name: desafio_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: desafio_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  backend:
    build: ./backend
    container_name: desafio_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@db:5432/desafio_db
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend-angular:
    build: ./frontend-angular
    container_name: desafio_frontend_angular
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data:
